### ISSUE TITLE
Can't run scripts

### ISSUE THREAD

**Issue by l4l** [fabsx00/python-joern#14]
I followed installing instructions but still there's a problem with requests via python (same issue with [joern-tools](https://github.com/fabsx00/joern-tools)

From sample script

``` python
#!/bin/python2

from joern.all import JoernSteps

j = JoernSteps()
j.setGraphDbURL('http://localhost:7474/db/data/')

j.connectToDatabase()

res =  j.runGremlinQuery('getFunctionsByName("main")')

for r in res: print r
```

Following backtrace:

```
Traceback (most recent call last):
  File "./launch.py", line 17, in <module>
    res =  j.runGremlinQuery('getFunctionsByName("main")')
  File "/usr/lib/python2.7/site-packages/joern-0.1-py2.7.egg/joern/all.py", line 44, in runGremlinQuery
    return self.gremlin.execute(finalQuery)
  File "/usr/lib/python2.7/site-packages/py2neo/ext/gremlin/__init__.py", line 36, in execute
    response = self.resources["execute_script"].post({"script": script})
  File "/usr/lib/python2.7/site-packages/py2neo/core.py", line 316, in post
    raise_from(self.error_class(message, **content), error)
  File "/usr/lib/python2.7/site-packages/py2neo/util.py", line 235, in raise_from
    raise exception
py2neo.error.NoClassDefFoundError: javax/transaction/SystemException
```

There's only one related [link](https://listserv.gwdg.de/pipermail/joern-users/2015/000010.html) in google. The possible issue there is non-installed Gremlin-plugin for Neo4j server. But, well, it's there:

``` bash
$ cat /var/log/neo4j/console.log | grep Gremlin | tail -n 2
2016-06-07 13:10:25.060+0300 INFO  Loaded server plugin "GremlinPlugin"
2016-06-07 13:10:25.061+0300 INFO    GraphDatabaseService.execute_script: execute a Gremlin script with 'g' set to the Neo4j2Graph and 'results' containing the results. Only results of one object type is supported.
```

Tried both: compiling&installing gremlin from source and installing from [snapshot](http://mlsec.org/joern/lib/neo4j-gremlin-plugin-2.1-SNAPSHOT-server-plugin.zip) from docs

Additional note: I use Arch Linux and grub neo4j from [aur](https://aur.archlinux.org/packages/neo4j-community/) and it installs the server separately (_/usr/lib/neo4j_, _/usr/share/java/neo4j_, _/usr/share/neo4j_, etc) so that can be the problem

**Comment by sandikast** [comment]
Me too. I wonder if  you have solved this confusing problem?

**Comment by l4l** [comment]
Yeah, I've definitely solved that problem.

afair i've just installed older neo4j from
[here](https://neo4j.com/artifact.php?name=neo4j-community-2.1.8-unix.tar.gz)
and used gremlin from the
[mlsec](http://mlsec.org/joern/lib/neo4j-gremlin-plugin-2.1-SNAPSHOT-server-plugin.zip)

There's some compatibility problems with newer versions of server.

I'm going to close that issue, but anyway feel free to ask additional
questions

**Comment by sandikast** [comment]
It`s so nice of you to answer me. I`ll have a try.

**Comment by mozark24** [comment]
Edit:  Actually, I'm still having a problem executing the basic python script from where you were.  They script now runs but produces no output (positive or negative).  No idea where to go from here and I've been working on this for 2 days...

Any help would be appreciated.

Neo4j 2.1.8
py2neo 2.0
py2neo-gremlin 0.1

In-case anyone else stumbles on this thread with an issue.  Here are some instructions on what to do with the snapshot:  https://github.com/neo4j-contrib/gremlin-plugin to use the gremlin snapshot
