### ISSUE TITLE
Need to update joern-lookup for being compatible with py2neo v3

### ISSUE THREAD

**Issue by AntoineHus** [fabsx00/python-joern#16]
So I tried to use joern-lookup and I had a failure with the dependencies. I was with py2neo 3, so I installed py2neo v2 and it solved the issue. 
We need to update python-joern or joern-tools for being compatible with py2neo 3.

**Comment by fabsx00** [comment]
Joern is currently moving to OrientDB, so I wouldn't want to spend any more time on updating to py2neo. Thanks for reporting this though.
