### ISSUE TITLE
Usage of wildcards to find calls

### ISSUE THREAD

**Issue by tbender** [fabsx00/python-joern#5]
I was trying to use python-joern to query the graph for dangerous methods.  As suggested in the [documentation](http://joern.readthedocs.org/en/latest/querying.html). 

However I found the methods getCallsTo and queryNodeIndex do not behave as expected. I found that the only way to get all calls to functions including 'cpy' was to use getNodesWithTypeAndCode.:

from joern.all import JoernSteps
```python
j = JoernSteps()
j.setGraphDbURL("http://localhost:7474/db/data/")
j.connectToDatabase()
#res = j.runGremlinQuery("getCallsTo('strcpy')") # WORKS!
#res = j.runGremlinQuery("getCallsTo('*cpy*')") # DOES NOT
#res = j.runGremlinQuery('getNodesWithTypeAndCode("Callee","strcpy")') #WORKS
res = j.runGremlinQuery('getNodesWithTypeAndCode("Callee","*cpy*")') #WORKS
#res = j.runGremlinQuery('queryNodeIndex("type:Callee AND name:*cpy*")') # DOES NOT
#res = j.runGremlinQuery('queryNodeIndex("type:Callee AND name:strcpy")') # DOES NOT
#res = j.runGremlinQuery('queryNodeIndex("*")') # DOES NOT, causes NPE
print(res)
for r in res:
	print r
```

Looking into the groovy code I found that you explicitly filter out the wildcard operator in  getCallsTo.

Could you elaborate on that?

**Comment by fabsx00** [comment]
Hi,
thanks for reporting this. For getCallsTo, I'm not sure when we decided to filter wildcards. I will reconsider this.

For queryNodeIndex, it needs to be:

res = j.runGremlinQuery('queryNodeIndex("type:Callee AND code:*cpy*")')

that is, the field is called 'code', not 'name'. That should work, and should be what you're looking for.

**Comment by tbender** [comment]
Hi, tahnks for the quick response! You're right. I could have spotted the $NODE_CODE: 

```python
Object.metaClass.getNodesWithTypeAndCode = { type, code ->
	query = "$NODE_TYPE:$type AND $NODE_CODE:$code"
	queryNodeIndex(query)
}
```
So I guess that is a bug in the documentation then?

**Comment by fabsx00** [comment]
yup, fixed. Although not entirely, as for the getCallsTo example, I've just replaced "cpy" by "memcpy" now since getCallsTo seems to not support wildcards anymore. I'll see what the reasons for filtering wildcards were and update the documentation accordingly. Again, thanks for reporting this.

**Comment by tbender** [comment]
Thanks guys. Please make sure the online docs at http://joern.readthedocs.org/en/latest/querying.html are updated as well. I used those all the time (and I am probably not alone with that) since they where one of the first hits on Google.

**Comment by fabsx00** [comment]
Sure. The documentation is built automatically when pushing commits. You may need to refresh your browser tab though.

**Comment by tbender** [comment]
Okay. Seems I just refreshed to early. Now changes are online. Thx ;)

**Comment by fabsx00** [comment]
getCallsTo accepts wildcards again now, and I have updated the documentation accordingly.
See https://github.com/fabsx00/python-joern/commit/b46e164b17ac3ac9173c1d85beaee6ea7b28433a

**Comment by er4z0r** [comment]
Works as promised. Thank you
