### ISSUE TITLE
C code/graphs aren't present in the repo for unit test cases

### ISSUE THREAD

**Issue by vlad902** [fabsx00/python-joern#9]
I see you have unit tests but I don't see the test cases anywhere. If you checked them in I would love to add tests for my steps as I go.

**Comment by fabsx00** [comment]
The test-code is currently shared between 'joern' and 'python-joern' and present in the joern repository:
https://github.com/fabsx00/joern/tree/master/testCode
To create the test-database ('.testDB'), you can use this script:
https://github.com/fabsx00/joern/blob/master/rebuildTestDB.sh
